### ISSUE TITLE
Error 400 Invalid event listener id

### ISSUE THREAD

**Issue by URBANsUNITED** [dubocr/homebridge-tahoma#114] opened 2019-07-11 06:26 UTC
Good morning,

a new error in my brand new Homebridge setup.
Started installing Homebridge totally from the scratch on my rpi3b with buster.
All went smooth, everything is proper installed, but now I see this in my logfile:

Homebridge restarted as root user:

```
Jul 11 07:20:28 raspberrypi homebridge[12377]: [7/11/2019, 7:20:28 AM] [Tahoma] Listener registered df79c90c-d9b6-8679-4e89-dcbd48dc3032
Jul 11 07:20:28 raspberrypi homebridge[12377]: [7/11/2019, 7:20:28 AM] [Tahoma] Listener registered df79c90f-d9b6-8679-4e89-dcbd0c1d6032

…

Jul 11 07:20:38 raspberrypi homebridge[12377]: [7/11/2019, 7:20:38 AM] [Tahoma] Error 400 Invalid event listener id : df79c90f-d9b6-8679-4e89-dcbd0c1d6032 (UNSPECIFIED_ERROR)
Jul 11 07:20:38 raspberrypi homebridge[12377]: [7/11/2019, 7:20:38 AM] [Tahoma] Error with listener df79c90f-d9b6-8679-4e89-dcbd0c1d6032 => Error 400 Invalid event listener id : df79c90f-d9b6-8679-4e89-dcbd0c1d6032 (UNSPECIFIED_ERROR)
```

What is this?

I see all my devices including all my Tahoma devices except one room. They simply do not refresh. Even not by switch through the rooms and then come back to the problematic room. And then out of the sudden, they refresh and show their values.

Best regards

URBANsUNITED

**Comment by dubocr** [comment] 2019-07-11 09:01
Hi,

This error is related to refreshing system. I've made some change to fix it. Can you please update and tell me if this occurs again.
Rooms are not supported in homebridge. Can you tell me which device is concerned.

Thanks

**Comment by URBANsUNITED** [comment] 2019-07-11 09:09
Thanks for directly taking care!
I will update this evening.

Problematic devices:
io Light sensors = Sunis wirefree io
original Zwave power switches #1822487

Thanks

**Comment by URBANsUNITED** [comment] 2019-07-11 16:51
Updated to 0.37, error still existing:

```
[7/11/2019, 6:49:30 PM] [Tahoma] Listener registered e1f09caa-3626-5439-0836-33d0daee36dc
[7/11/2019, 6:49:30 PM] [Tahoma] Listener already registered, drop e1f09cbc-3626-5439-0836-33d0ca7fddfa
[7/11/2019, 6:49:30 PM] [Küche-Licht] Küche-Licht ( POWER ) - Power from Status OFF
[7/11/2019, 6:49:30 PM] [Tahoma] Listener registered e1f09caa-3626-5439-0836-33d0daee36dc
[7/11/2019, 6:49:30 PM] [Tahoma] Listener already registered, drop e1f09cbc-3626-5439-0836-33d0ca7fddfa

[7/11/2019, 6:49:40 PM] [Tahoma] Error 400 Invalid event listener id : e1f09caa-3626-5439-0836-33d0daee36dc (UNSPECIFIED_ERROR)
[7/11/2019, 6:49:40 PM] [Tahoma] Error 400 Invalid event listener id : e1f09caa-3626-5439-0836-33d0daee36dc (UNSPECIFIED_ERROR)
[7/11/2019, 6:49:40 PM] [Tahoma] Error with listener e1f09caa-3626-5439-0836-33d0daee36dc => Error 400 Invalid event listener id : e1f09caa-3626-5439-0836-33d0daee36dc (UNSPECIFIED_ERROR)
[7/11/2019, 6:49:40 PM] [Tahoma] Error with listener e1f09caa-3626-5439-0836-33d0daee36dc => Error 400 Invalid event listener id : e1f09caa-3626-5439-0836-33d0daee36dc (UNSPECIFIED_ERROR)
```

**Comment by dubocr** [comment] 2019-07-15 18:03
Hi,

I've fix some things in the last release. Can you update and tell me if better ?

Thanks

**Comment by Seb0101** [comment] 2019-07-18 10:57
Hi,
For me the problem is still here. More immediate than before : it appears just after the startup, before it sas delayed.

**Comment by URBANsUNITED** [comment] 2019-07-21 09:38
Hi!
Only one listener, but error still exists:
[Tahoma] Error 400 No registered event listener (UNSPECIFIED_ERROR)
[7/21/2019, 11:34:44 AM] [Tahoma] Error with listener 13e2064e-3626-5439-0836-33d09a4c52c1 => Error 400 No registered event listener (UNSPECIFIED_ERROR

Is it important? Or can we simply ignore it?

Btw. had good results with my light sensors in the past days. But I had the config on refreshrate 300 and no  "alwaysPoll": true & "pollingPeriod": 10
Just chang back to alwayspoll to see the differences

Thanks

**Comment by URBANsUNITED** [comment] 2019-07-21 17:20
> Btw. had good results with my light sensors in the past days. But I had the config on refreshrate 300 and no "alwaysPoll": true & "pollingPeriod": 10
Just chang back to alwayspoll to see the differences

Change back to "refreshPeriod": 300
Lots of device were unavailable with above code

**Comment by koupus** [comment] 2019-07-21 18:06
Bonjour Romain,

mon log sur mac au cas ou cela peut t'aider

[7/21/2019, 11:43:22 AM] Homebridge is running on port 51826.
[7/21/2019, 11:43:52 AM] [Tahoma] Error 400 No registered event listener (UNSPECIFIED_ERROR)
[7/21/2019, 11:43:52 AM] [Tahoma] Error with listener 13ea11a6-3626-5439-0836-33d00a975194 => Error 400 No registered event listener (UNSPECIFIED_ERROR)
[7/21/2019, 12:13:22 PM] [Tahoma] RESP : {"success":true,"roles":[{"name":"ENDUSER"}]}
[7/21/2019, 12:13:22 PM] [Tahoma] Listener registered 14058922-3626-5439-0836-33d038179e62

Bien à toi, Thomas.

**Comment by dubocr** [comment] 2019-08-11 13:11
Hi,

This is fully fixed in last release 0.3.11. Let me know if you have any more trouble.

Bonjour Thomas,

Tout est corrigé dans la dernière version. N'hésites pas si tu rencontre encore des problèmes.

Désolé pour le délais.

**Closed** 2019-08-11 13:12 UTC

**Comment by koupus** [comment] 2019-08-11 20:00
Bonsoir Romain la mise à jour du plugin a malheureusement fait sauté ma visualisation de mes accessoires dans Homekit. Meme après redémarrage de mon mac. Aucune erreur dans le log! Bizarre🤔

**Comment by dubocr** [comment] 2019-08-11 20:12
Bonsoir,

Rien du tout dans les logs même après redémarrage ? Y à t'il quand même quelques logs d'initialisation ?
`sudo journalctl | grep homebridge`
`sudo journalctl | grep homebridge | grep Tahoma`

**Comment by koupus** [comment] 2019-08-12 13:42
Bonjour Romain, le terminal m' indique que "journalctl" n'est pas une commande valide... 
Voici cependant le lot au démarrage (qui ne me semble pas different des précédents quand cela fonctionnait) : 
[8/12/2019, 5:10:58 AM] Loaded config.json with 0 accessories and 3 platforms.
[8/12/2019, 5:10:59 AM] Loaded plugin: homebridge-tahoma
homebridge-tahoma API version: 2.4
[8/12/2019, 5:10:59 AM] Registering platform 'homebridge-tahoma.Tahoma'
[8/12/2019, 5:10:59 AM] [Tahoma] Initializing Tahoma platform...
[8/12/2019, 5:10:59 AM] [Tahoma] Fetch accessories...
[8/12/2019, 5:10:59 AM] [Tahoma] Logging in to TaHoma server...
[8/12/2019, 5:11:00 AM] [Tahoma] Listener registered 83cebf4f-3626-5439-51c1-05c230598896
[8/12/2019, 5:11:00 AM] [Tahoma] [Alarm] type: Alarm > TSKAlarmController, protocol: internal
[8/12/2019, 5:11:00 AM] [Tahoma] Instanciate Alarm as Alarm
[8/12/2019, 5:11:00 AM] [Tahoma] [Active button] type: Pod > Pod, protocol: internal
[8/12/2019, 5:11:00 AM] [Tahoma] No definition found for Pod > Pod in mapping.json file
[8/12/2019, 5:11:00 AM] [Tahoma] [Salle de Jeux] type: OccupancySensor > OccupancySensor, protocol: io
[8/12/2019, 5:11:00 AM] [Tahoma] Instanciate Salle de Jeux as OccupancySensor
[8/12/2019, 5:11:00 AM] [Tahoma] [Porte Entrée] type: ContactSensor > ContactSensor, protocol: io
[8/12/2019, 5:11:00 AM] [Tahoma] Instanciate Porte Entrée as ContactSensor
[8/12/2019, 5:11:00 AM] [Tahoma] [SDJ Fenetre] type: RollerShutter > PositionableRollerShutter, protocol: io
[8/12/2019, 5:11:00 AM] [Tahoma] Instanciate SDJ Fenetre as WindowCovering
[8/12/2019, 5:11:00 AM] [Tahoma] [SDJ Porte] type: RollerShutter > PositionableRollerShutter, protocol: io
[8/12/2019, 5:11:00 AM] [Tahoma] Instanciate SDJ Porte as WindowCovering
[8/12/2019, 5:11:00 AM] [Tahoma] [Salon] type: OccupancySensor > OccupancySensor, protocol: io
[8/12/2019, 5:11:00 AM] [Tahoma] Instanciate Salon as OccupancySensor
[8/12/2019, 5:11:00 AM] [Tahoma] [Garage] type: OccupancySensor > OccupancySensor, protocol: io
[8/12/2019, 5:11:00 AM] [Tahoma] Instanciate Garage as OccupancySensor
[8/12/2019, 5:11:00 AM] [Tahoma] [Salon Droit] type: RollerShutter > PositionableRollerShutter, protocol: io
[8/12/2019, 5:11:00 AM] [Tahoma] Instanciate Salon Droit as WindowCovering
[8/12/2019, 5:11:00 AM] [Tahoma] [Sirene] type: Siren > IOSiren, protocol: io
[8/12/2019, 5:11:00 AM] [Tahoma] Instanciate Sirene as Switch
[8/12/2019, 5:11:00 AM] [Tahoma] [Salon Gauche] type: RollerShutter > PositionableRollerShutter, protocol: io
[8/12/2019, 5:11:00 AM] [Tahoma] Instanciate Salon Gauche as WindowCovering
[8/12/2019, 5:11:00 AM] [Tahoma] [Cuisine] type: RollerShutter > PositionableRollerShutter, protocol: io
[8/12/2019, 5:11:00 AM] [Tahoma] Instanciate Cuisine as WindowCovering
[8/12/2019, 5:11:00 AM] [Tahoma] [Salon Baie] type: RollerShutter > PositionableRollerShutter, protocol: io
[8/12/2019, 5:11:00 AM] [Tahoma] Instanciate Salon Baie as WindowCovering
[8/12/2019, 5:11:00 AM] [Tahoma] [Jardin] type: Camera > MyFoxSecurityCamera, protocol: myfox
[8/12/2019, 5:11:00 AM] [Tahoma] No definition found for Camera > MyFoxSecurityCamera in mapping.json file
[8/12/2019, 5:11:00 AM] [Tahoma] [Jardin-1] type: Light > StatefulOnOffLight, protocol: myfox
[8/12/2019, 5:11:00 AM] [Tahoma] Instanciate Jardin-1 as Lightbulb
[8/12/2019, 5:11:00 AM] [Tahoma] [Jardin] type: Alarm > MyFoxAlarmController, protocol: myfox
[8/12/2019, 5:11:00 AM] [Tahoma] Instanciate Jardin as ["Alarm","OccupancySensor"]
[8/12/2019, 5:11:00 AM] [Tahoma] [Remote] type: RemoteController > AlarmRemoteController, protocol: rtds
[8/12/2019, 5:11:00 AM] [Tahoma] No definition found for RemoteController > AlarmRemoteController in mapping.json file
[8/12/2019, 5:11:00 AM] [Tahoma] [Porte de Garage] type: GarageDoor > UpDownGarageDoor4T, protocol: rts
[8/12/2019, 5:11:00 AM] [Tahoma] Instanciate Porte de Garage as GarageDoorOpener
[8/12/2019, 5:11:00 AM] [Tahoma] Initializing platform accessory 'Porte de Garage'...
[8/12/2019, 5:11:00 AM] [Tahoma] Initializing platform accessory 'Jardin'...
[8/12/2019, 5:11:00 AM] [Tahoma] Initializing platform accessory 'Salon Baie'...
[8/12/2019, 5:11:00 AM] [Tahoma] Initializing platform accessory 'Cuisine'...
[8/12/2019, 5:11:00 AM] [Tahoma] Initializing platform accessory 'Salon Gauche'...
[8/12/2019, 5:11:00 AM] [Tahoma] Initializing platform accessory 'Sirene'...
[8/12/2019, 5:11:00 AM] [Tahoma] Initializing platform accessory 'Salon Droit'...
[8/12/2019, 5:11:00 AM] [Tahoma] Initializing platform accessory 'Garage'...
[8/12/2019, 5:11:00 AM] [Tahoma] Initializing platform accessory 'Salon'...
[8/12/2019, 5:11:00 AM] [Tahoma] Initializing platform accessory 'SDJ Porte'...
[8/12/2019, 5:11:00 AM] [Tahoma] Initializing platform accessory 'SDJ Fenetre'...
[8/12/2019, 5:11:00 AM] [Tahoma] Initializing platform accessory 'Porte Entrée'...
[8/12/2019, 5:11:00 AM] [Tahoma] Initializing platform accessory 'Salle de Jeux'...
[8/12/2019, 5:11:00 AM] [Tahoma] Initializing platform accessory 'Alarm'...
[8/12/2019, 5:11:00 AM] [Tahoma] Initializing platform accessory 'Jardin-1'...

**Comment by koupus** [comment] 2019-08-13 12:01
Bonjour Romain, c'est finalement résolu! Tout est réapparu... Je ne sais pas ce qu'il s'est passé mais le principal est que cela fonctionne!
Merci, Thomas

**Comment by dubocr** [comment] 2019-08-14 09:53
Effectivement il n'y avait rien d'anormal dans les logs et j'allais essayé de copier ta config. Mais tant mieux alors. J'espère que tout devrait rentrer dans l'ordre.
